"""empty message

Revision ID: 236e4975cd7f
Revises: b4b7bff294bc
Create Date: 2021-04-17 12:48:49.238337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '236e4975cd7f'
down_revision = 'b4b7bff294bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('image', sa.String(length=255), nullable=False))
    op.add_column('events', sa.Column('image', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'image')
    op.drop_column('businesses', 'image')
    # ### end Alembic commands ###
