"""empty message

Revision ID: b4b7bff294bc
Revises: 91d6b50e14ef
Create Date: 2021-04-16 17:53:34.952536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4b7bff294bc'
down_revision = '91d6b50e14ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('attendees', sa.String(length=30), nullable=True))
    op.drop_column('events', 'attendee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('attendee', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_column('events', 'attendees')
    # ### end Alembic commands ###
