export const GET_ALL_BUSINESS = 'GET_ALL_BUSINESS'
export const GET_BUSINESS_DETIALS = 'GET_BUSINESS_DETAILS'
export const GET_BUSINESSES_BY_ZIPCODE = 'GET_BUSINESSES_BY_ZIPCODE'
export const UPLOAD_BUSINESS = 'UPLOAD_BUSINESS'

export const GET_ALL_EVENT = 'GET_ALL_EVENT'
export const GET_EVENT_DETAILS = 'GET_EVENT_DETAILS'
export const GET_EVENTS_BY_ZIPCODE = 'GET_EVENTS_BY_ZIPCODE'
export const UPLOAD_EVENT = 'UPLOAD_EVENT'

export const USER_ID = 'USER_ID'
export const USER_BUSINESSES_AND_EVENTS = 'USER_BUSINESSES_AND_EVENTS'
export const DELETE_BUSINESS = 'DELETE_BUSINESS'
export const DELETE_EVENT = 'DELETE_EVENT'
export const UPDATE_EVENT = 'UPDATE_EVENT'
export const UPDATE_BUSINESS = 'UPDATE_BUSINESS'

export const UPDATE_FORM_FIELD = 'UPDATE_FORMF_FIELD'

export const AUTHENCTICATED = 'AUTHENTICATED'
export const CURRENT_USER = 'CURRENT_USER'
export const AUTH_FORM = 'AUTH_FORM'
export const REGISTER = 'REGISTER'
export const LOGIN = 'LOGIN'
export const TOGGLE_REGISTER_COMPLETE = 'TOGGLE_REGISTER_COMPLETE'

export const ADDRESS_TO_COORDINATES = 'ADDRESS_TO_COORDINATES'
export const CONVERTER_INPUT = 'CONVERTER_INPUT'
