export const GET_ALL_BUSINESS = 'GET_ALL_BUSINESS'
export const GET_BUSINESS_DETIALS = 'GET_BUSINESS_DETAILS'
export const GET_ALL_EVENT = 'GET_ALL_EVENT'
export const GET_EVENT_DETAILS = 'GET_EVENT_DETAILS'
